bugfix (reported by 'geom'):   "The following exception occurs when trying to update working copy with Unicode (multi-byte)   file names from file:///path/to repository:
  org.tmatesoft.svn.core.SVNException: svn: Invalid report for top level of working copy
    at org.tmatesoft.svn.core.internal.wc.SVNErrorManager.error(SVNErrorManager.java:49)
    at org.tmatesoft.svn.core.internal.io.fs.FSUpdateContext.drive(FSUpdateContext.java:233)
    at org.tmatesoft.svn.core.internal.io.fs.FSRepository.finishReport(FSRepository.java:1020)
    at org.tmatesoft.svn.core.internal.wc.admin.SVNReporter.report(SVNReporter.java:104)
    at org.tmatesoft.svn.core.internal.io.fs.FSRepository.update(FSRepository.java:773)
    at org.tmatesoft.svn.core.wc.SVNUpdateClient.doUpdate(SVNUpdateClient.java:162)
        ...
   Additional Information 	Root cause of exception is in 
   org.tmatesoft.svn.core.internal.io.fs.FSUpdateContext class writePathInfoToReportFile() 
   method. The code uses String.length() method to determine number of bytes should be written 
   to report file. Obviously, it works for ISO-8859 strings only."